// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Counters$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Counters",
  "sourceName": "@openzeppelin/contracts/utils/Counters.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220a07dd85af0b1723417cd50ad78af559c02f53f125a983233ccd469e18905ed0964736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea2646970667358221220a07dd85af0b1723417cd50ad78af559c02f53f125a983233ccd469e18905ed0964736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Counters",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Counters.sol:Counters",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Counters",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Counters$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Counters.sol:Counters",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Counters$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Counters",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Counters.sol:Counters",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Counters$Type["abi"]>>;
}
