// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AcademicRecords$Type } from "./AcademicRecords";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AcademicRecords"]: AcademicRecords$Type;
    ["contracts/AcademicRecords.sol:AcademicRecords"]: AcademicRecords$Type;
  }

  interface ContractTypesMap {
    ["AcademicRecords"]: GetContractReturnType<AcademicRecords$Type["abi"]>;
    ["contracts/AcademicRecords.sol:AcademicRecords"]: GetContractReturnType<AcademicRecords$Type["abi"]>;
  }
}
